### GET request with a header
GET http://localhost:3000/api/server-feature-todo
Accept: application/json


### Send POST request with json body
POST http://localhost:3000/api/server-feature-todo
Content-Type: application/json

{
  "completed": false,
  "description": "bar",
  "id": "todo-3827",
  "title": "foo"
}
